replicas: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

fullnameOverride: pizza-chart

appImage: shayelbazwork/hiredscore-public
appImageTag: main
imagePullPolicy: IfNotPresent
restartPolicy: Always
clusterRoleName: pizza-app-role
serviceAccountName: pizza-app-sa

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false


service:
  httpPort: 8080
  httpTargetPort: 5000

livenessProbe:
  httpGet:
    path: "/health"
    port: httpport
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: "/health"
    port: httpport
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"

terminationGracePeriodSeconds: 30

volumeMountPath: "/mnt/data"

persistence:
  enabled: true 
  volumeName: pizza-app
  volumeClaimName: "pizza-order-claim"
  type: local

 
  local:
    storageClassName: manual
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/home/data"



 # nfs:
  #   storageClassName: efs-sc
  #   capacity:
  #     storage: 5Gi
  #   volumeMode: Filesystem
  #   accessModes:
  #     - ReadWriteMany
  #   persistentVolumeReclaimPolicy: Retain
  #   csi:
  #     driver: efs.csi.aws.com
  #     volumeHandle: fs-087fd49e4e6612df0
