apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pizza-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pizza
  minReplicas: 1
  maxReplicas: 3  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70